
enum{
    ENABLE_CHG = 0,
    DISABLE_CHG,
    GET_VBAT,
    CHK_GPS,
    GET_GPS_INFO,
    CHK_NFC,
    INIT_NFC_AS_ADAPTER,
    GET_NFC_TAGID,
    GET_NFC_NDEF,
    SET_NFC_NDEF,
    ERASE_NFC_NDEF,
    INIT_NFC_AS_TAG,
    COMMANDS_CNT
};